framework:
    mailer:
        envelope:
            sender: 'svc.smtp.imp@anton-paar.com'
        headers:
            From: 'imp Plattform <svc.smtp.imp@anton-paar.com>'
        dsn: '%env(MAILER_DSN)%'
        #dsn: 'smtp://localhost' 
